export const Constants = {
    freesloganmakerHeading:'Free Slogan Maker',
freesloganmakerSubHeading:'Simply enter a term that describes your business, and get up to 1,000 relevant slogans for free.',
sloganSearchHeading:'Word for your slogan',
sloganButtonText:'Generate Slogan',
sloganCountText:'We have generated 1,023 slogans for “cozy”',
downloadAllSlogansText:'Download all',
downloadPcVersion:'Dukaan for PC',
searchFeatureText:'Search',
searchFeature:'Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.',
selectFeature:'Select',
selectFeatureContent:'Choose from thousands of options generated by the slogan maker that fit your needs.',
standOutFeature:'Stand out',
standOutFeatureContent:`Congrats on your new slogan. It's time to win the world!`,
freeProductsTitle:'Try our other free products',
};

export const footerContent={
    footerLinks:['Contact','Tutorial','Privacy','About', 'Facebook',`FAQ's`,'Blog','Banned Items','Jobs','Twitter',' ',' ',' ',' ','Linkedin'],
    allRightsReserved:'Dukaan 2020, All rights reserved.',
    madeInIndia:'Made in'
}